### ISSUE TITLE
Cannot find module 'angular' when compiling with gulp and browserify

### ISSUE THREAD

**Issue by goodbomb** [jtblin/angular-chart.js#220]
Hey guys,

I'm having an issue compiling with browserify. I'm seeing this error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'angular' from '/Users/benscott/WebDev/Projects/open-source/angular-gulp-browserify-starter/libs/angular-chart.js/dist'
    at /Users/benscott/WebDev/Projects/open-source/angular-gulp-browserify-starter/node_modules/resolve/lib/async.js:46:17
    at process (/Users/benscott/WebDev/Projects/open-source/angular-gulp-browserify-starter/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/benscott/WebDev/Projects/open-source/angular-gulp-browserify-starter/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/benscott/WebDev/Projects/open-source/angular-gulp-browserify-starter/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/benscott/WebDev/Projects/open-source/angular-gulp-browserify-starter/node_modules/resolve/lib/async.js:92:31)
    at /Users/benscott/WebDev/Projects/open-source/angular-gulp-browserify-starter/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

I've tried with and without shimming, with no luck. Any ideas? My app compiles fine without chart.js

**Comment by jtblin** [comment]
How did you install it? You'd need to use npm to install for browserify to
work I believe.

**Comment by goodbomb** [comment]
I wouldn't think that would be the case. I have angular and a bunch of other bower installations all working fine with browserify by using the bowerify module.

**Comment by goodbomb** [comment]
```
'./libs/angular/angular.js',
            './libs/angular-animate/angular-animate.js',
            './libs/angular-bootstrap/ui-bootstrap-tpls.js',
            './libs/angular-cookies/angular-cookies.js',
            './libs/angular-resource/angular-resource.js',
            './libs/angular-sanitize/angular-sanitize.js',
            './libs/angular-ui-router/release/angular-ui-router.js',
            './libs/jquery/dist/jquery.js',
            './libs/bootstrap/dist/js/bootstrap.js',
            './libs/domready/ready.js',
            './libs/lodash/lodash.js',
            './libs/restangular/dist/restangular.js'
```

All of those files are installed with bower and they work fine with browserify and the bowerify module.

**Comment by jtblin** [comment]
Maybe you want to ask on Stackoverflow with the full code. Hard to say with this.

**Comment by vapits** [comment]
@goodbomb Did you find a solution on that? I have exactly the same error here.
