### ISSUE TITLE
TypeError: (intermediate value)[type] is not a function error

### ISSUE THREAD

**Issue by niemyjski** [jtblin/angular-chart.js#389]
The following stack over flow issue pretty much sums it up except for I'm using an angular 1.5 component and the base chart (pulling in from master 2.0 branch)

http://stackoverflow.com/questions/37028578/typeerror-intermediate-valuetype-is-not-a-function-error

```html
<canvas class="chart chart-base"
        chart-type="$ctrl.type"
        chart-series="$ctrl.labels"
        chart-data="$ctrl.data"
        chart-labels="$ctrl.labels"
        chart-legend="true">
</canvas>
```

```js
  angular
    .module('abc.chart')
    .component('chart', {
      bindings: {
        title: '@',
        filter: '@',
        options: '@',
        type: '@',
        aggregations: '<'
      },
      templateUrl: 'components/chart/chart-component.tpl.html',
      controller: ChartController
    });


  /* @ngInject */
  function ChartController(statService) { // populates data }
```

```html
        <div class="panel-body">
          <chart type="bar" title="test" aggregations="vm.aggregations"></chart>
        </div>
```

**Comment by niemyjski** [comment]
```js
angular.js:13550 TypeError: (intermediate value)[type] is not a function
    at createChart (http://localhost:9001/bower_components/angular-chart.js/dist/angular-chart.js:199:49)
    at resetChart (http://localhost:9001/bower_components/angular-chart.js/dist/angular-chart.js:177:13)
    at Scope.$digest (http://localhost:9001/bower_components/angular/angular.js:17073:23)
    at Scope.$apply (http://localhost:9001/bower_components/angular/angular.js:17337:24)
    at http://localhost:9001/bower_components/angular/angular.js:17633:22
    at completeOutstandingRequest (http://localhost:9001/bower_components/angular/angular.js:5869:10)
    at http://localhost:9001/bower_components/angular/angular.js:6145:7
    at wrapped (http://localhost:9001/bower_components/exceptionless/dist/exceptionless.js:63:25) undefined(anonymous function) @ angular.js:13550$delegate.(anonymous function) @ angular.js:33(anonymous function) @ angular.js:10225(anonymous function) @ angular.js:25Scope.$digest @ angular.js:17091Scope.$apply @ angular.js:17337(anonymous function) @ angular.js:17633completeOutstandingRequest @ angular.js:5869(anonymous function) @ angular.js:6145wrapped @ exceptionless.js:63setTimeout (async)traceKitAsyncExtension @ exceptionless.js:1212Browser.self.defer @ angular.js:6143scheduleApplyAsync @ angular.js:17632Scope.$applyAsync @ angular.js:17366done @ angular.js:11569completeRequest @ angular.js:11778requestLoaded @ angular.js:11711XMLHttpRequest.send (async)(anonymous function) @ angular.js:11756sendReq @ angular.js:11517serverRequest @ angular.js:11227processQueue @ angular.js:15961(anonymous function) @ angular.js:15977Scope.$eval @ angular.js:17229Scope.$digest @ angular.js:17045(anonymous function) @ angular.js:17268completeOutstandingRequest @ angular.js:5869(anonymous function) @ angular.js:6145wrapped @ exceptionless.js:63setTimeout (async)traceKitAsyncExtension @ exceptionless.js:1212Browser.self.defer @ angular.js:6143Scope.$evalAsync @ angular.js:17266(anonymous function) @ angular.js:15869scheduleProcessQueue @ angular.js:15977extend.$$resolve @ angular.js:16010extend.resolve @ angular.js:15993resolveFn @ angular.js:16218(anonymous function) @ angular.js:5681(anonymous function) @ angular.js:5739forEach @ angular.js:322AnimateRunner._resolve @ angular.js:5738(anonymous function) @ angular.js:5731(anonymous function) @ angular.js:5576requestAnimationFrame (async)(anonymous function) @ angular.js:16255waitForTick @ angular.js:5574(anonymous function) @ angular.js:5584AnimateRunner @ angular.js:5641queueAnimation @ angular-animate.js:2468$animate.push @ angular-animate.js:2411enter @ angular.js:5398_start @ loading-bar.js:221(anonymous function) @ loading-bar.js:100(anonymous function) @ angular.js:19157completeOutstandingRequest @ angular.js:5869(anonymous function) @ angular.js:6145wrapped @ exceptionless.js:63
```


<img width="1156" alt="screen shot 2016-05-16 at 4 28 01 pm" src="https://cloud.githubusercontent.com/assets/1020579/15304493/47e01a32-1b83-11e6-956e-f859ede3fb77.png">

**Comment by niemyjski** [comment]
Doh, was doing a pull request which changed to a local fork of the branch. I'm just a nub today.
