### ISSUE TITLE
Bar and radar charts throwing errors, line chart not appearing, doughnut and pie charts working fine, all using same data

### ISSUE THREAD

**Issue by SHDavies** [jtblin/angular-chart.js#408]
Here's a plnkr: https://plnkr.co/edit/mmWo3xYnzcHCoD8KD4eE?p=preview

I'm using angular 1.5.3 with components, and using the same data for all available charts, only doughnut and pie charts are working. Line charts just don't appear, and the errors for bar and radar charts are:

BAR:
`TypeError: Cannot read property 'length' of undefined
    at Object.buildScale (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.1.1/Chart.js:2450:25)
    at Object.initialize (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.1.1/Chart.js:2379:9)
    at Object.Chart.Type (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.1.1/Chart.js:914:19)
    at Object.ChartType (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.1.1/Chart.js:1149:18)
    at Chart.(anonymous function) [as Bar] (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.1.1/Chart.js:1177:12)
    at d (https://cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.min.js:1:3387)
    at https://cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.min.js:1:4394
    at Scope.$digest (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.3/angular.js:16869:23)
    at Scope.$apply (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.3/angular.js:17133:24)
    at done (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.3/angular.js:11454:47)`

RADAR:
`TypeError: Cannot read property '0' of undefined
    at Object.buildScale (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.1.1/Chart.js:3586:31)
    at Object.initialize (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.1.1/Chart.js:3469:9)
    at Object.Chart.Type (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.1.1/Chart.js:914:19)
    at Object.ChartType (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.1.1/Chart.js:1149:18)
    at Chart.(anonymous function) [as Radar] (https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.1.1/Chart.js:1177:12)
    at d (https://cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.min.js:1:3387)
    at https://cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.min.js:1:4394
    at Scope.$digest (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.3/angular.js:16869:23)
    at Scope.$apply (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.3/angular.js:17133:24)
    at done (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.3/angular.js:11454:47)`

I've tried passing the data into the charts several ways, including just hardcoding an array literal into the chart-data and chart-label attributes, with the same result each time.

**Comment by jtblin** [comment]
Man just read the docs... line, bars, and radars need multidimensional arrays e.g. `this.materialTypeData = [[60, 50, 40]];`
