### ISSUE TITLE
Using with browserify

### ISSUE THREAD

**Issue by omarfouad** [jtblin/angular-chart.js#97]
I'm using the npm module version, but I get a console error saying that `Chart` is not defined, because that's obviously a dependency. Now I try to shim Chart.js (the one that comes with the bower package with angular-chart.js) but I still can't get it to work.

```json

 "browser": {
    "Chart": "./bower_components/Chart.js/Chart.js"
  },
  "browserify-shim": {
    "Chart": "Chart"
  }
```

Any ideas? 

Thanks in advance.

**Comment by jantimon** [comment]
#95 was already merged - as soon as it is published to bower and npm it should work without shim

**Comment by jtblin** [comment]
Done. Thanks @jantimon for that :+1:

**Comment by omarfouad** [comment]
Thanks guys.

**Comment by goodbomb** [comment]
Hey guys,

I'm having an issue compiling with browserify. I'm seeing this error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'angular' from '/Users/benscott/WebDev/Projects/open-source/angular-gulp-browserify-starter/libs/angular-chart.js/dist'
    at /Users/benscott/WebDev/Projects/open-source/angular-gulp-browserify-starter/node_modules/resolve/lib/async.js:46:17
    at process (/Users/benscott/WebDev/Projects/open-source/angular-gulp-browserify-starter/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/benscott/WebDev/Projects/open-source/angular-gulp-browserify-starter/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/benscott/WebDev/Projects/open-source/angular-gulp-browserify-starter/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/benscott/WebDev/Projects/open-source/angular-gulp-browserify-starter/node_modules/resolve/lib/async.js:92:31)
    at /Users/benscott/WebDev/Projects/open-source/angular-gulp-browserify-starter/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

I've tried with and without shimming, with no luck. Any ideas?
